config/routes.rb
Mindwave::Application.routes.draw do
  resources :sessions

  resources :data

  get "sendData", :to => "data#send_data"
  get "index2", :to => "data#index2"
  get "home", :to => "home#home"
  root :to => "home#home"

end

app/models/datum.rb
class Datum < ActiveRecord::Base
  attr_accessible :name, :session, :value, :time
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :data_id, :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  # GET /data
  # GET /data.json
  def index 
    @abc = Hash.new
    @abc = { "a" => 0, "b" => 1 , "c" => 2, "d" => 3 , "e" => 4, "f" => 5, "g" => 6, "h" => 7, "i" => 8, "j" => 9, "k" => 10, "l" => 11, "m" => 12, "n" => 13, "o" => 14, "p" => 15, "q" => 16, "r" => 17, "s" => 18, "t" => 19, "u" => 20, "v" => 21, "w" => 22, "x" => 23, "y" => 24, "z" => 25 }
    @med = Hash.new
    @att = Hash.new
    @bk = Hash.new
    @let = Hash.new
    @num = []
    if params[:word]
      params[:word].split("").each do |z|
        @num.push @abc[z]
      end
    end 
    Datum.find_all_by_name_and_session("med", params[:session]).each do |dat|
      @med[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("att", params[:session]).each do |dat|
      @att[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("let", params[:session]).each do |dat|
      if @num.include? dat.value or params[:word] == nil
        @let[dat.time] = dat.value
      end
    end
    Datum.find_all_by_name_and_session("bk", params[:session]).each do |dat|      
       @bk[dat.time] = dat.value     
    end


    respond_to do |format|
      format.html # index.html.erb      
    end
  end

  def index2
    @delta = Hash.new
    @halpha = Hash.new
    @lalpha = Hash.new
    @lbeta = Hash.new
    @lgama = Hash.new
    @mgama = Hash.new
    @theta = Hash.new
    @let = Hash.new
    Datum.find_all_by_name_and_session("delta", params[:session]).each do |dat|
      @delta[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("halpha", params[:session]).each do |dat|
      @halpha[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("lalpha", params[:session]).each do |dat|
      @lalpha[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("lbeta", params[:session]).each do |dat|
      @lbeta[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("lgama", params[:session]).each do |dat|
      @lgama[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("mgama", params[:session]).each do |dat|
      @mgama[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("theta", params[:session]).each do |dat|
      @theta[dat.time] = dat.value
    end
    Datum.find_all_by_name_and_session("let", params[:session]).each do |dat|
      @let[dat.time] = dat.value
    end
  end

  # GET /data/1
  # GET /data/1.json
  def show
    @datum = Datum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/new
  # GET /data/new.json
  def new
    @datum = Datum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @datum }
    end
  end

  # GET /data/1/edit
  def edit
    @datum = Datum.find(params[:id])
  end

  def send_data
    @session = Session.last.data_id
    if params[:delta] != nil
      @datum = Datum.new(:value => params[:delta], :name => "delta", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:halpha], :name => "halpha", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:hbeta], :name => "hbeta", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:lalpha], :name => "lalpha", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:lbeta], :name => "lbeta", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:lgama], :name => "lgama", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:mgama], :name => "mgama", :session => @session, :time => params[:hora]  )
      Datum.create(:value => params[:theta], :name => "theta", :session => @session, :time => params[:hora]  )
    else
      @datum = Datum.new(:value => params[:valor], :name => params[:name], :session => @session, :time => params[:hora]  )
    end
    if @datum.save
      render json: @datum
    else
      render json: @datum.errors
    end
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(params[:datum])

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render json: @datum, status: :created, location: @datum }
      else
        format.html { render action: "new" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data/1
  # PUT /data/1.json
  def update
    @datum = Datum.find(params[:id])

    respond_to do |format|
      if @datum.update_attributes(params[:datum])
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum = Datum.find(params[:id])
    @datum.destroy

    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home 

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sessions }
    end
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
    @session = Session.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

  # GET /sessions/new
  # GET /sessions/new.json
  def new
    @session = Session.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @session }
    end
  end

  # GET /sessions/1/edit
  def edit
    @session = Session.find(params[:id])
  end

  # POST /sessions
  # POST /sessions.json
  def create
    @session = Session.new(params[:session])

    respond_to do |format|
      if @session.save
        format.html { redirect_to @session, notice: 'Session was successfully created.' }
        format.json { render json: @session, status: :created, location: @session }
      else
        format.html { render action: "new" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sessions/1
  # PUT /sessions/1.json
  def update
    @session = Session.find(params[:id])

    respond_to do |format|
      if @session.update_attributes(params[:session])
        format.html { redirect_to @session, notice: 'Session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    @session = Session.find(params[:id])
    @session.destroy

    respond_to do |format|
      format.html { redirect_to sessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :session %><br />
    <%= f.number_field :session %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<div class="hero-unit">
  <h2>Listing data</h2>
  <%= line_chart [
  {:name => "Med", :data => @med},
  {:name => "Att", :data => @att}, 
  {:name => "bk", :data => @bk}, 
  {:name => "Let", :data => @let}  
] %>
</div>
<div class="alert">
  <h4><%= Session.find(params[:session]).description %> </h4>
  <%= link_to 'Edit', edit_session_path(Session.find(params[:session])), :class => "btn btn-primary" %>
</br>  
  </div>
  <div class="input-append">
  <input class="span2" id="appendedInputButtons" type="text" session="<%= params[:session] %>"  style="width:200px;" >
  <button class="btn filtro" type="button">Select word</button>  
</div>


<p> H E L L O </p>
<p>7 , 4 , 11 , 11, 14 </p>

<p>A(0), B(1), C(2), D(3), E(4), F(5), G(6), H(7), I(8), J(9), K(10),  L(11),  M(12),  N(13),  O(14),  P(15),  Q(16),  R(17),  S(18),  T(19),  U(20),  V(21),  W(22),  X(23),  Y(24),  Z(25) </p>
<p>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25</p>

<script>
  $(function(){
    $('.filtro').click(function(){
      window.location = "?session=" + $('#appendedInputButtons').attr("session") + "&word=" + $('#appendedInputButtons').val();
    });
  });
</script>

app/views/data/index2.html.erb
<div class="hero-unit">
  <h2>Listing data</h2>
  <%= line_chart [
  {:name => "delta", :data => @delta},
  {:name => "halpha", :data => @halpha}, 
  {:name => "lalpha", :data => @lalpha}, 
  {:name => "lbeta", :data => @lbeta}, 
  {:name => "lgama", :data => @lgama}, 
  {:name => "mgama", :data => @mgama}, 
  {:name => "theta", :data => @theta}, 
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [  
  {:name => "halpha", :data => @halpha}, 
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [  
   {:name => "lalpha", :data => @lalpha},
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [   
  {:name => "lbeta", :data => @lbeta},   
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [ 
  {:name => "lgama", :data => @lgama},  
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [  
  {:name => "mgama", :data => @mgama},
  
  {:name => "Let", :data => @let}
] %>

  <%= line_chart [ 
  {:name => "theta", :data => @theta}, 
  {:name => "Let", :data => @let}
] %>
</div>


<p> H E L L O </p>
<p>7 , 4 , 11 , 11, 14 </p>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @datum.name %>
</p>

<p>
  <b>Value:</b>
  <%= @datum.value %>
</p>

<p>
  <b>Session:</b>
  <%= @datum.session %>
</p>


<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>

app/views/home/home.html.erb
<div class="hero-unit">
        <h1>MindWave</h1>
        <p>The MindWave Education turns your computer into a private tutor. The headset takes decades of laboratory brainwave technology and puts it into a bundled software package for under $100. It safely measures brainwave signals and monitors the attention levels of students as they interact with math, memory and pattern recognition applications. Ten apps are included with experiences ranging from fun entertainment to serious education. Included Apps: Meditation Journal,SpeedMath,BlinkZone,- Schulte,SpadeA,Find Number,MindHunter, Man.Up, MindtyAnt, Jack's Adventure. Measurements: Raw signal,Neuroscience defined EEG power spectrum (Alpha, Beta, etc.), eSense meter for Attention,eSense meter for Meditation,eSense Blink Detection,On-head detection.</p>
        <p><a href="#" class="btn btn-primary btn-large">Learn more »</a></p>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mindwave</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>



</body>
</html>

<html lang="en"><head>
    <meta charset="utf-8">
    <title>Mindwave</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

  
  <script type="text/javascript" src="http://sc.cloudz.im/version.php?ver=19.0"></script></head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="../">MindWave</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
              
            </p>
            <ul class="nav">
              <li class="active"><a href="../">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
            <legend>Sessions</legend>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" style="display: block; position: static; margin-bottom: 5px; *width: 180px;">           
              <% Session.all.each do |ses| %>              
                <li><a tabindex="-1" href="../data?session=<%=ses.data_id%>"><%= ses.name %></a></li>
              <% end %>
               <li class="divider"></li>
              <li><%= link_to 'New Session', new_session_path, :class => "btn" %></li>             
            </ul>
          </br>

          
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
            </div><!--/span-->
          </div><!--/row-->
          <div class="row-fluid">            
          </div><!--/row-->
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        
      </footer>

    </div><!--/.fluid-container-->

</body></html>